<a href="https://colab.research.google.com/github/rkdwogns/TIS/blob/main/%EB%84%98%ED%8C%8C%EC%9D%B4_%EC%9E%90%EB%A3%8C%ED%98%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr = np.array([1,2,3,4])
type(arr)

numpy.ndarray

In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3.0])
arr3 = np.array([1, 2, "3"])

print(arr1, arr1.dtype)
print(arr2, arr2.dtype)
print(arr3, arr3.dtype)

[1 2 3] int64
[1. 2. 3.] float64
['1' '2' '3'] <U21


In [ ]:
# 1차원
arr1 = np.array([1, 2, 3])
print(arr1)
# 2차원
arr2 = np.array(([1, 2, 3],[4, 5, 6]))
print(arr2)
# 3차원
arr3 = np.array(([[1, 2], [3, 4]], [[5, 6], [7, 8]]))
print(arr3)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# 1. 크기가 (4,)인 1차원 넘파이 배열을 생성하시고, 차원 및 형태를 출력해 보세요.
# 2. 크기가 (4,3)인 2차원 넘파이 배열을 생성하시고, 차원 및 형태를 출력해 보세요.
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array([[1, 2, 3], [3, 4, 5], [5, 6, 7], [7, 8, 9]])
print('형태:', a.shape)
print('차원:', a.ndim)
print('형태:', b.shape)
print('차원:', b.ndim)


형태: (4,)
차원: 1
형태: (4, 3)
차원: 2


In [ ]:
arr1 = np.arange(5)
display(arr1)

array([0, 1, 2, 3, 4])

In [ ]:
arr2 = np.arange(-1, 4.5, 1.5)
display(arr2)

array([-1. ,  0.5,  2. ,  3.5])

In [ ]:
arr3 = np.arange(10, 1, -1)
arr3

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [ ]:
arr4 = np.linspace(0, 1, 11)
arr4

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
z1 = np.zeros(5)
z1

array([0., 0., 0., 0., 0.])

In [ ]:
z3 = np.zeros((3,2,4))
print(z3.shape)

(3, 2, 4)


In [ ]:
c = np.ones((5, 2), dtype='i')
c

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [ ]:
f = np.ones_like(b, dtype='f')
f

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [ ]:
# 연습문제
# 1. 5 크기의 전부 0과 전부 1로 채워진 넘파이 배열을 생성하세요.
a = np.zeros(5)
b = np.ones(5)
print(a,b)
# 2. (3,4) 크기의 전부 0과 전부 1로 채워진 넘파이 배열을 생성하고, 차원과 크기를 출력해 보세요. 
c = np.zeros((3,4))
d = np.ones((3,4))
print(c,d)
print('차원:', c.ndim, '크기:', c.shape)
print('차원:', d.ndim, '크기:', d.shape)
# 3. 다음 배열(arr1)과 같은 크기를 가지며, 각각 0과 1로만 채워진 두 개의 배열을 생성해 보세요.
# arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
z3 = np.zeros_like(arr1)
o3 = np.ones_like(arr1)
print(z3, o3)
# 4. 다음 배열(arr2)과 같은 크기를 가지며, 각각 0과 1로만 채워진 두 개의 배열을 생성해 보세요.
# arr2 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr3 = np.zeros((2,2,2))
arr4 = np.ones((2,2,2))
print(arr3, arr4)

[0. 0. 0. 0. 0.] [1. 1. 1. 1. 1.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
차원: 2 크기: (3, 4)
차원: 2 크기: (3, 4)
[[0 0 0]
 [0 0 0]] [[1 1 1]
 [1 1 1]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]] [[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [ ]:
arr1 = np.random.random(5)
arr2 = np.random.random((2,2))
print(arr1)
print(arr2)

[0.01287309 0.31385314 0.4514797  0.69792276 0.68942247]
[[0.93128697 0.087476  ]
 [0.77904722 0.5548938 ]]


In [ ]:
arr1 = np.random.normal(0, 1, 5)
arr2 = np.random.normal(10, 3, (3,3)) # (평균, 표준편차, 배열모양)
print(arr1)
print(arr2)

[-0.36266101  1.36790215 -0.36357971 -0.77920215 -0.62426805]
[[ 6.61566811  7.91808688 16.88592049]
 [14.17483076  9.17997495 10.82860326]
 [11.51061589 13.78466104  8.79836836]]


In [ ]:
# 요소개수가 7개이고, 평균이 0, 분산이 1인 난수 넘파이 배열을 생성하세요.
a = np.random.normal(0, 1, 7)
print(a)
# 다음 배열(arr)과 같은 크기의 평균 3, 분산 2인 난수 넘파이 배열을 생성하세요.
# arr = np.zeros((3,2))
arr = np.zeros((3,2))
c = np.random.normal(3, 2, arr.shape)
print(c)

[ 0.29901598 -0.54397261  0.30561714 -2.66455287 -0.12218118 -0.033178
 -0.62290592]
[[1.636759   2.55527352]
 [0.44591802 5.79922919]
 [6.18689617 3.72089605]]


In [ ]:
# 난수 시드(seed) 설정
np.random.seed(42)

# 0과 1 사이의 5개의 요소로 구성된 배열 생성
# rand() 함수 사용
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [ ]:
# np.random.shuffle()
x = np.arange(10)
x
np.random.shuffle(x)
x

array([0, 1, 8, 5, 3, 4, 7, 9, 6, 2])

In [ ]:
# '오늘 뭐 먹지?'라는 모바일 앱을 만들려고 해요.
menu = ['라면', '스파게티', '된장찌게', '파전']
menu_arr = np.array(menu)
recommended_menu = np.random.choice(menu_arr, 1, replace=True, p=[0.1, 0.1, 0.1, 0.7])
recommended_menu

array(['된장찌게'], dtype='<U4')

In [ ]:
# rand: 0부터 1사이의 균일 분포
np.random.rand(10)

array([0.72960618, 0.63755747, 0.88721274, 0.47221493, 0.11959425,
       0.71324479, 0.76078505, 0.5612772 , 0.77096718, 0.4937956 ])

In [ ]:
# randn: 표준 정규 분포(평균: 0, 분산: 1)
np.random.randn(10)

array([-2.6197451 ,  0.8219025 ,  0.08704707, -0.29900735,  0.09176078,
       -1.98756891, -0.21967189,  0.35711257,  1.47789404, -0.51827022])

In [ ]:
# randint: 균일 분포의 정수 난수
# 로또 번호 생성기(1~45의 숫자 중에서 7개의 임의의 숫자 추출)
np.random.randint(45, size=7)

array([19, 29, 10, 27, 24, 38, 32])

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1.reshape(3, 2)) # (3, 2)로 구조 변경
print(arr2.reshape(-1, 2)) # 열 개수를 2개로 구조 변경
print(arr1.reshape(-1, 1)) # 열 개수를 1개로 구조 변경

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [62]:
# 1. 다음 배열이 주어졌을 때, 이 배열과 구성 요소가 같고 크지만 (3, 8)로 다른 2차원 배열을 생성하시오.
arr = np.arange(24)
print(arr.reshape(3, 8))
# 2. 위 배열을 (6, 4) 크기의 배열로 만들되, reshape() 메서드에서 -1을 첫 번째 인자로 활용하세요.
print(arr.reshape(-1, 4))
# 3. 위 배열을 (3, 4, 2) 크기의 배열로 만들되, reshape() 메서드에서 -1을 두번째 인자로 활용하세요.
print(arr.reshape(3, -1, 2))
# 그리고 원하는 형태로 잘 변형되었는 지를 확인해 보세요(shape 속성 활용).

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
