<a href="https://colab.research.google.com/github/rkdwogns/TIS/blob/main/%EC%9C%A0%EB%8B%88%EB%B2%84%EC%84%A4_%ED%95%A8%EC%88%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
a + b

array([5, 7, 9])

In [4]:
import numpy as np
x1 = np.random.random(10 ** 6)
x2 = np.random.random(10 ** 6)

In [5]:
%%timeit
a = x1 + x2 # ms = 1/1000 second

1.4 ms ± 267 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [7]:
x = np.arange(4)
y = np.linspace(1, 10, 4)
print("x     =", x)
print("y     =", y)
print("x + 5 =", x + 5)
print("x + y =", x + y)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x * y =", x * y)
print("x / 2 =", x / 2)
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

x     = [0 1 2 3]
y     = [ 1.  4.  7. 10.]
x + 5 = [5 6 7 8]
x + y = [ 1.  5.  9. 13.]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x * y = [ 0.  4. 14. 30.]
x / 2 = [0.  0.5 1.  1.5]
-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [10]:
# 연습문제 : 1~100까지 1씩 증가하는 원소(요소)로 구성된 넘파이 배열이 있다.
# 1. 각각의 요소에 3제곱한 새로운 배열을 생성하시오.
# 힌트: arange(1,101)
x = np.arange(1, 101)
print("x ** 3 =", x ** 3)
# 2. 각각의 요소를 제곱근을 취한 새로운 배열을 생성하시오.
# 힌트: 제곱근 구하는 함수는 np.sqrt()
a = np.sqrt(x)
print("a = ", a)
# 3. 각각의 원소에 10을 더한 새로운 배열 생성하시오.
print('x + 10 =', x + 10)

x ** 3 = [      1       8      27      64     125     216     343     512     729
    1000    1331    1728    2197    2744    3375    4096    4913    5832
    6859    8000    9261   10648   12167   13824   15625   17576   19683
   21952   24389   27000   29791   32768   35937   39304   42875   46656
   50653   54872   59319   64000   68921   74088   79507   85184   91125
   97336  103823  110592  117649  125000  132651  140608  148877  157464
  166375  175616  185193  195112  205379  216000  226981  238328  250047
  262144  274625  287496  300763  314432  328509  343000  357911  373248
  389017  405224  421875  438976  456533  474552  493039  512000  531441
  551368  571787  592704  614125  636056  658503  681472  704969  729000
  753571  778688  804357  830584  857375  884736  912673  941192  970299
 1000000]
a =  [ 1.          1.41421356  1.73205081  2.          2.23606798  2.44948974
  2.64575131  2.82842712  3.          3.16227766  3.31662479  3.46410162
  3.60555128  3.74165739  3

In [12]:
x = np.array([-2, -1, 0, 1, 2])
print('abs(x) = ', abs(x))

abs(x) =  [2 1 0 1 2]


In [19]:
# 연습
# 다음 배열의 각각의 3을 곱하고 1을 뺀 함수를 정의하여 배열에 적용하시오.
arr = np.arange(10)
def plus_three_minus_one(x):
  return x * 3 - 1
print(plus_three_minus_one(arr))

[-1  2  5  8 11 14 17 20 23 26]


In [20]:
x = np.array([1, 2, 3])
y = np.array([1, 3, -2])
print("x == y: ", x == y)

x == y:  [ True False False]


In [21]:
print(sum(x >= 2))

2


In [29]:
# 연습문제
# 다음 배열에서 짝수인 요소의 개수를 출력하는 코드를 작성하세요.
arr = np.arange(45)
print('개수:',sum(arr % 2 == 0))

개수: 23


In [30]:
a = np.array([[1, 2], [3, 4]]) # 2차원 배열, 즉 행렬
b = np.array([-1, -2]) # 1차원 배열, 즉 벡터
print(a + b)

[[0 0]
 [2 2]]
