<a href="https://colab.research.google.com/github/rkdwogns/TIS/blob/main/%EC%9D%B8%EB%8D%B1%EC%8B%B1%2C_%EC%8A%AC%EB%9D%BC%EC%9D%B4%EC%8B%B1ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
X = [[1, 2],[3, 4]]
X = np.array(X)
print(X)
print(X[0,1])

[[1 2]
 [3 4]]
2


In [12]:
X = np.array([[1, 2, 3], [3, 4, 5], [5, 6, 7]])
# print(X)
display('X배열:',X)
print('='*20)
print(X[1, 1]) # 0행 1열에 있는 값 출력
print(X[:,2]) # 모든 행, 2번째 열

'X배열:'

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

4
[3 5 7]


In [15]:
# 다음 넘파이 배열 대상으로 요구하는 행과 열을 추출하시오.
arr = np.arange(30).reshape(5,6)
# 1번째 행 추출
# 0번째 열 추출
# 1번째~3번쨰 행, 0번째~2번째 열 추출
# 2번째 행, 3번째~5번째 열 추출
# 2번째~4번째 행, 3번째 열 추출
print(arr[1])
print(arr[:,0])
print(arr[1:4, 0:3])
print(arr[2,3:6])
print(arr[2:5,3])

[ 6  7  8  9 10 11]
[ 0  6 12 18 24]
[[ 6  7  8]
 [12 13 14]
 [18 19 20]]
[15 16 17]
[15 21 27]


In [28]:
# 오늘의 메뉴를 넘파이 인덱싱 및 슬라이싱 활용하여 추출하기
weekly_menu = [['백미밥/잡곡밥', '육개장', '두부양념조림', '할라마요함박스테이크', '시금치고추장무침', '콩나물볶음/포기김치'],
               ['백미밥/잡곡밥', '김치수제비', '부대햄야채볶음', '야채계란찜', '수제양념깻잎지', '건파래볶음/포기김치'] ,
               ['백미밥/잡곡밥','배추된장국','닭볶음탕(김치)','사각어묵야채볶음','브로콜리,물미역&초장','상추겉절이/포기김치'],
               ['백미밥/잡곡밥', '돈육김치찌개', '김치스파게티', '청파래생선까스 & 어니언소스', '느타리', '미역줄기볶음/포기김치'],
               ['백미밥/잡곡밥', '콩나물김치국', '간장불고기', '야채비빔만두', '도토리묵&달래장', '부추겉절이']]
weekly_menu
weekly_menu_arr = np.array(weekly_menu)
print(weekly_menu_arr.shape)

(5, 6)


In [32]:
# 인덱싱이나 슬라이싱을 이용하여 오늘(수요일)의 메뉴들을 출력하시오
print(weekly_menu_arr[2,:])
# 인덱싱이나 슬라이싱을 이용하여 오늘(수요일)의 국을 출력하시오
print(weekly_menu_arr[2,1])
# 인덱싱이나 슬라이싱을 이용하여 이번 주의 국을 모두 출력하시오
print(weekly_menu_arr[:,1])

['백미밥/잡곡밥' '배추된장국' '닭볶음탕(김치)' '사각어묵야채볶음' '브로콜리,물미역&초장' '상추겉절이/포기김치']
배추된장국
['육개장' '김치수제비' '배추된장국' '돈육김치찌개' '콩나물김치국']


In [33]:
# 전치(transpose): 행과 열을 서로 바꿈
weekly_menu_arr_transposed = weekly_menu_arr.T
print(weekly_menu_arr_transposed.shape)

(6, 5)


In [34]:
x = np.array([1,2,3,4,5])
b = [True, False, True, True, False]
print(x[b])

[1 3 4]


In [38]:
# 연습문제1
# 다음 배열에서 5보다 작은 요소들만 추출하시오.
a = np.arange(10)
print(a[a < 5])
# 위 배열에서 짝수인 요소들만 추출하시오.
# 힌트: % 연산자 활용 (a % 2 == 0)
print(a[a % 2 == 0])

[0 1 2 3 4]
[0 2 4 6 8]


In [7]:
# 연습문제2
import numpy as np
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
# 이 배열에서 3의 배수를 찾아라
print(x[x % 3 == 0])
# 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라
print(x[(x % 3 == 0) & (x % 4 == 1)])

[ 3  6  9 12 15 18]
[9]
