<a href="https://colab.research.google.com/github/rkdwogns/TIS/blob/main/%EC%A7%91%EA%B3%84%ED%95%A8%EC%88%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
x = np.arange(15).reshape(5, 3)
# 행 방향 계산
print(np.sum(x, axis=0))
print(x.sum(axis=0))
# 열 방향 계산
print(np.sum(x, axis=1))
print(x.sum(axis=1))

[30 35 40]
[30 35 40]
[ 3 12 21 30 39]
[ 3 12 21 30 39]


In [4]:
# 다음 리스트를 넘파이 배열로 전환하고, 평균과 중앙값을 구하시오.
import numpy as np
a_list = [1, 3, 5, 7, 100]
arr = np.array(a_list)
print(arr)

[  1   3   5   7 100]


In [8]:
print(np.mean(arr), np.median(arr))

23.2 5.0


In [9]:
# quantile(4분위수)

arr = np.arange(1,101)
np.quantile(arr, 0.75)

75.25

In [11]:
# 연습문제
# 다음 배열에 unique() 함수를 적용해 보시오.
arr = np.array([1,3,5,7,9,3,5,100])
np.unique(arr)

array([  1,   3,   5,   7,   9, 100])

In [14]:
# 연습문제1
# 다음과 같은 리스트 자료가 있다. 넘파이 배열로 전환하고, 다음 통계량들을 구하시오.
# 평균, 표준편차, 중앙값, 최대값, 최소값
a_list = list(range(30))
arr = np.array(a_list)
print(np.mean(arr), np.std(arr), np.median(arr), np.max(arr), np.min(arr))

14.5 8.65544144839919 14.5 29 0


In [28]:
# 연습문제2
# 위 리스트를 (5,6) 크기의 넘파이 배열로 전환하고, 열별, 행별 통계량을 구하시오.
a_list = list(range(30))
x = arr.reshape(5, 6)
# 열별: axis=0
print(f'열별 평균: {np.mean(x, axis=0)}')
print(f'열별 표준편차: {np.std(x, axis=0)}')
print(f'열별 중위수: {np.median(x, axis=0)}')
print(f'열별 최대: {np.max(x, axis=0)}')
print(f'열별 최소: {np.min(x, axis=0)}')
print("==== 행별 통계량 ====")
# 행별: axis=1 (열방향)
print(f'행별 평균: {np.mean(x, axis=1)}')
print(f'행별 표준편차: {np.std(x, axis=1)}')
print(f'행별 중위수: {np.median(x, axis=1)}')
print(f'행별 최대: {np.max(x, axis=1)}')
print(f'행별 최소: {np.min(x, axis=1)}')

열별 평균: [12. 13. 14. 15. 16. 17.]
열별 표준편차: [8.48528137 8.48528137 8.48528137 8.48528137 8.48528137 8.48528137]
열별 중위수: [12. 13. 14. 15. 16. 17.]
열별 최대: [24 25 26 27 28 29]
열별 최소: [0 1 2 3 4 5]
==== 행별 통계량 ====
행별 평균: [ 2.5  8.5 14.5 20.5 26.5]
행별 표준편차: [1.70782513 1.70782513 1.70782513 1.70782513 1.70782513]
행별 중위수: [ 2.5  8.5 14.5 20.5 26.5]
행별 최대: [ 5 11 17 23 29]
행별 최소: [ 0  6 12 18 24]
